### ISSUE TITLE
LTV non-repudiation error

### ISSUE THREAD

**Issue by milouk** [MatthiasValvekens/pyHanko#10]
Hello Matthias, 

First of all great work you have done with pyHanko.

**Describe the bug**
We are planning on using pyHanko on a large scale for signed pdf docs for the Greek public sector. For that we need
the signed documents to be LTV enabled. I have tried to make an initial implementation but when I use the param `embed_validation_info` I get an `pyhanko.sign.general.SigningError: ("The signer's certificate could not be validated", InvalidCertificateError('The X.509 certificate provided is not valid for the purpose of non repudiation'))` error. 

**To Reproduce**
The code I have written so far looks like this 

```
    cms_signer = signers.SimpleSigner.load_pkcs12(
        certificate_filename, passphrase=password.encode('utf-8'))
    
    w = IncrementalPdfFileWriter(pdf_buffer)
    tst_client = timestamps.HTTPTimeStamper('https://timestamp.aped.gov.gr/qtss')

    sv = fields.SigSeedValueSpec(
        reasons=[],
        digest_methods=[],
        flags=3,
    )

    sp = fields.SigFieldSpec('Signature', seed_value_dict=sv, box=(15, 705, 175, 798))

    image = PdfImage(image=settings.STAMP_IMAGE)

    style = TextStampStyle(background=image, border_width=0)
    
    vc = ValidationContext(trust_roots=[cms_signer.signing_cert])
    
    out = signers.PdfSigner(signature_meta=signers.PdfSignatureMetadata(
                                            field_name='Signature',
                                            reason='My reason',
                                            location='My location',
                                            use_pades_lta=True,
                                            subfilter=fields.SigSeedSubFilter.PADES,
                                            embed_validation_info=True,
                                            validation_context=vc
                                            ),
                            signer=cms_signer,
                            timestamper=tst_client,
                            stamp_style=style,
                            new_field_spec=sp
                            ).sign_pdf(w)
```

Where the `certificate_filename` is a p12 signing certificate and `pdf_buffer` is the document I want to sign in BytesIO

**Expected behavior**
In the end I expect a signed document that when opened with Adobe Acrobat Reader it is listed as "LTV enabled"

**Screenshots**
<img width="993" alt="Screenshot 2021-03-13 at 21 50 35" src="https://user-images.githubusercontent.com/22796276/111042450-277cce80-8446-11eb-8d96-47ad32552086.png">

**Environment (please complete the following information):**
 - Docker with python:3.7 image
 - MacOS 11.2.2
 
**Additional context**
The same issue exists in both 0.4.0 as well as 0.5.0-dev1

I have contaced HARICA which is the Hellenic Academic & Research Institutions Certification Authority and they told me that non-repudiaton has nothing to do with LTV and it shouldn't be needed to LTV enable a document.

**Comment by milouk** [comment]
Quick Update: 

I used this flag `signer_key_usage={'digital_signature'},` and now it works, but Adobe still says it is NOT LTV enabled.

**Comment by MatthiasValvekens** [comment]
Hi milouk, thanks for checking in!

Your first issue is indeed due to the fact that pyHanko (by default) requires signer certificates to have the nonRepudiation key usage bit set. However, some CAs exclusively use the digitalSignature bit instead (whether that's an appropriate decision is a matter for debate). As ta validator it is of course your prerogative to determine which key usages you consider appropriate, so you can override that default (and it seems that you've found out how that works, so that's OK).

As for your second issue: from the error message I'm seeing here, I guess that the time stamping authority that you're using is not supplying all certificates in its chain of trust. This isn't a hard requirement of the time stamping protocol, so that sometimes happens. What you can then do is try to track down the relevant certificate(s) yourself, and add them to the `ValidationContext` you're using to handle signing/validating. I found a certificate with a subject line that matches the missing one here: http://pki.aped.gov.gr/ca/APEDRoot.crt. Chances are that adding that one to the `ValidationContext` will do the trick.

Hope this helps, if anything's still unclear, feel free to ask. :)

**Comment by milouk** [comment]
Thanks for the very quick and detailed reply and for your research as well. 

What you proposed indeed worked and I got the document signed but it still shows as "Signature is not LTV enabled" in Adobe. Am I missing something here?

<img width="656" alt="Screenshot 2021-03-14 at 00 17 43" src="https://user-images.githubusercontent.com/22796276/111051296-b4318780-845a-11eb-91bd-57d41d5e9769.png">

**Comment by MatthiasValvekens** [comment]
Hard to tell just from that screenshot, but I'm 90% sure that that's because the TSA authorising the timestamp is untrusted in Acrobat. You can fix that on your own machine by importing the root certificate from earlier into Acrobat's trust store (it's somewhere deep in the settings menu), but that won't necessarily help if you want these signatures to be verifiable by others as well. Regardless, if marking the TSA as trusted makes the signature LTV enabled, then you'll know that that was the problem.

Is there a reason why you have to use this particular TSA? If the platform you're targeting requires this specific TSA I would simply mark the relevant certificate as trusted and move on, but otherwise you might be better off looking for a TSA that is more widely trusted (e.g. one authorised by a certificate authority on the AATL or EUTL).

**Comment by milouk** [comment]
So I added it to trusted certificates as you mentioned and now I got this 
<img width="545" alt="Screenshot 2021-03-14 at 00 28 39" src="https://user-images.githubusercontent.com/22796276/111051512-3a9a9900-845c-11eb-88b3-06436e8a5d4c.png">

Is this considered an "LTV enabled" document although the "Rev 1" signature is not LTV enabled? 

PS: We are using this TSA as its the Greek Governments official TSA

**Comment by MatthiasValvekens** [comment]
Interesting. Then it could be due to missing revocation information for one of the intermediate certificates, perhaps. Can you send me a signed dummy file at pyhanko.samples <at mark goes here> mvalvekens.be?

Adobe's "LTV" criteria aren't officially documented, so this kind of thing is not always easy to debug.

**Comment by MatthiasValvekens** [comment]
Ah, wait, before you try all that: I noticed just now that you didn't add the `allow_fetching=True` parameter to your validation context. That's another potential reason.

Hmm, perhaps I should have pyHanko log a warning if `allow_fetching` is `False` when embedding revocation info...

**Comment by milouk** [comment]
Ah, thought about it as I was reading through the `ValidationContext` declaration but I thought it wouldn't make any difference. Im trying it now.

**Comment by MatthiasValvekens** [comment]
Ooh, I get it now! I should have read your code more carefully.

You marked the signer's certificate as a trust root in the validation context. This is very likely not what you want: in almost all trust models based on X.509, trust roots are absolute, and in particular things like "revocation status" and so on don't apply to them, so pyHanko doesn't fetch revocation info for trust roots (because that wouldn't make any sense).

You'll want to instead mark the highest relevant certificate in the chain as a trust root here; any intermediates go under `other_certs`. The signer's certificate doesn't need to be included in the validation context at all.

Fortunately, your cert seems to have been directly issued by a CA on the EUTL ("HARICA Qualified Legal Entities SubCA R3"), so marking that one as a trust root should work.

PS: after writing my previous comment I realised that the CLI won't help you in this case, since there's no way to get rid of the nonRepudiation key usage requirement from the CLI. That's on my roadmap of issues to fix, though.

**Comment by milouk** [comment]
Finally, this worked. 
Matthias thank you very much for your patience and for your help. I learned a lot. 
Cheers.

<img width="545" alt="Screenshot 2021-03-14 at 01 26 01" src="https://user-images.githubusercontent.com/22796276/111052535-3f634b00-8464-11eb-8be6-ab9151890f8b.png">

**Comment by louridas** [comment]
Hello Matthias,

First of all thanks (I am also at GRNET where we implement signing / validation services for the Greek public sector). Just a note for the non-repudiation bit. I think it is important to make it configurable, in order for the signatures to be compliant with the ETSI EN 319 412-2, section 4.3.2 (Key Usage) standard; there you can see the permitted combinations of Key Usage settings. The notes are particularly interesting.

In practice, non-repudiation is used with Qualified Electronic Signatures, not with Advanced Signatures.

Best Regards,

Panos.

**Comment by MatthiasValvekens** [comment]
Hi Panos,


Thanks for that! I was aware of the difference in semantics between digitalSignatures and nonRepudiation from X.509 / RFC 5280, but I didn't know of this specific call-out in the ESI standard.

Key usage constraints are already fully configurable in the API, but you've convinced me to make getting that into the CLI a priority (esp. for validation). It's not a lot of work---just a matter of exposing the right settings; I should be able to take care of that by the time 0.5.0 is released (which should be soon).

Thanks!

**Comment by inui-sdt2** [comment]
Dear Matthias

about signed pdf document validation
I am stucking in "The signer's certificate is untrusted." error(same as above).
I'm sure I'm setting the right one (root and int CA's).
I am also using signer_key_usage={'digital_signature'} at signing stage.

$ python3 verify.py 
The active key usage policy requires at least one of the key usage extensions non repudiation to be present.
Chain of trust validation for Common Name: xxxxx failed.

If there are any other possibilities, could you please advise?

`
root_cert = load_cert_from_pemder('/home/ubuntu/ws/hanko/class1-root-only.crt')
int_cert = load_cert_from_pemder('/home/ubuntu/ws/hanko/intca.crt')
tsa_root_cert = load_cert_from_pemder('/home/ubuntu/ws/hanko/tsa_cacert.pem')

vc = ValidationContext(
    trust_roots=[root_cert],
    other_certs=[int_cert]
    )

ts_vc = ValidationContext(
    trust_roots=[tsa_root_cert]
    )    

with open('signed-13.pdf', 'rb') as doc:
    r = PdfFileReader(doc)
    sig = r.embedded_signatures[0]
    status = validate_pdf_signature(sig, vc, ts_vc)
    print(status.pretty_print_details())
`

**Comment by MatthiasValvekens** [comment]
Hi @inui-sdt2 !

You need to tell the validator to accept the `digital_signature` key usage as well. Right now, pyHanko takes a conservative default position by rejecting all signer certificates that don't have the nonRepudiation/contentCommitment key usage bit set.

You can change that behaviour using the `key_usage_settings` argument to `validate_pdf_signature`. See here:

 - https://pyhanko.readthedocs.io/en/latest/api-docs/pyhanko.sign.validation.html#pyhanko.sign.validation.validate_pdf_signature
 - https://pyhanko.readthedocs.io/en/latest/api-docs/pyhanko.sign.general.html#pyhanko.sign.general.KeyUsageConstraints

In your case, you probably want to pass in `KeyUsageConstraints(key_usage={'digital_signature'})`.

I should probably add a few words to the library usage guide to make this part of the API a bit easier to find.

----------------

PS: If you have any follow-up questions, could you please create a thread in the [discussion space](https://github.com/MatthiasValvekens/pyHanko/discussions) instead? That makes it easier to keep the issue tracker somewhat organised :).

**Comment by BeardOverflow** [comment]
I had the same problem (_Signature is not LTV enabled and will expire after xxx_) using Sectigo's QTSA server. Fortunately, the comments in this issue helped me to configure the trust root/other certs properly.
```
trust_root_paths = [
  'ca/sectigo/Sectigo-Qualified-Time-Stamping-Root-R45.crt', # https://crt.sh/?id=3547980726
  'ca/sectigo/Sectigo-Qualified-Time-Stamping-CA-R35.crt', # https://crt.sh/?id=3547998112
]
other_certs_paths = [
  'ca/sectigo/Sectigo-Qualified-Time-Stamping-Signer-3.crt', # https://crt.sh/?id=9297382517
]
trust_roots = [ load_cert_from_pemder(each) for each in trust_root_paths ]
other_certs = [ load_cert_from_pemder(each) for each in other_certs_paths ]
```
My issue was using `Sectigo-Qualified-Time-Stamping-Signer-3.crt` as trust_root, but it have to go in other_certs!

**Comment by MatthiasValvekens** [comment]
For QTSPs, you should be able to find all relevant roots in the EU trust list browser: https://eidas.ec.europa.eu/efda/trust-services/browse/eidas/tls.

If you look for Sectigo qualified timestamping services, you'll eventually wind up at this root: https://eidas.ec.europa.eu/efda/trust-services/browse/eidas/tls/tl/ES/tsp/43/service/3. I didn't check in detail, but from a cursory look this corresponds to the one linked above.


FWIW, there's a [long-lived feature branch](https://github.com/MatthiasValvekens/pyHanko/tree/feature/qualified-certs) in pyHanko to make all this qualified services stuff a bit more "batteries included", but it's a bit too rough around the edges still to merge.

**Comment by BeardOverflow** [comment]
@theprogramsam 
I did a little of "reverse engineering". At first, I signed a document with Sectigo's QTSA server to review who had signed the timestamp: `Sectigo Qualified Time Stamping Signer #3`. Then, using crt.sh service, I found all the related certificates: signer certificate, intermediate QTSA CA and root CA. https://crt.sh/?q=Sectigo+Qualified+Time+Stamping

Both QTSA CA and root CA does are well documented: https://www.sectigo.com/uploads/files/Sectigo_eIDAS_TSPPS_v1.0.8.pdf and https://www.sectigo.com/uploads/files/eIDAS/Sectigo_eIDAS_CPS_v1.1.2.pdf, but signer certificate does not.
