### ISSUE TITLE
Generic processing error: invalid literal for int() with base 10: b'f'

### ISSUE THREAD

**Issue by gchehab** [MatthiasValvekens/pyHanko#16]
**Describe the bug**
Error on file parsing during validation of signed file.
```
>python -mpyhanko sign validate --pretty-print testdata\assinado_com_web_socket.pdf
2021-05-21 17:00:19,316 - pyhanko.cli - ERROR - Generic processing error.
Traceback (most recent call last):
  File "C:\Users\guilhermec\source\repos\pyHanko\pyhanko\cli.py", line 69, in pyhanko_exception_manager
    yield
  File "C:\Users\guilhermec\source\repos\pyHanko\pyhanko\cli.py", line 421, in validate_signatures
    r = PdfFileReader(infile)
  File "C:\Users\guilhermec\source\repos\pyHanko\pyhanko\pdf_utils\reader.py", line 605, in __init__
    self.read()
  File "C:\Users\guilhermec\source\repos\pyHanko\pyhanko\pdf_utils\reader.py", line 940, in read
    self._read_xrefs()
  File "C:\Users\guilhermec\source\repos\pyHanko\pyhanko\pdf_utils\reader.py", line 875, in _read_xrefs
    startxref = self._read_xref_stream()
  File "C:\Users\guilhermec\source\repos\pyHanko\pyhanko\pdf_utils\reader.py", line 825, in _read_xref_stream
    idnum, generation = read_object_header(stream, strict=self.strict)
  File "C:\Users\guilhermec\source\repos\pyHanko\pyhanko\pdf_utils\reader.py", line 447, in read_object_header
    return int(idnum), int(generation)
ValueError: invalid literal for int() with base 10: b'f'
Error: Generic processing error.
```

**To Reproduce**
`python -mpyhanko sign validate --pretty-print testdata\assinado_com_web_socket.pdf`
[assinado_com_web_socket.pdf](https://github.com/MatthiasValvekens/pyHanko/files/6524865/assinado_com_web_socket.pdf)

**Expected behavior**
File should be invalid, unless added the AC file to the trusted file 

**Environment (please complete the following information):**
 - OS: Windows 10 and Ubuntu 20.10, python 3.9.5
 - Version: current HEAD

**Comment by MatthiasValvekens** [comment]
Yeah, this file is malformed. The `startxref` pointer should point to the `x` in `xref`, but instead it points to the last `5` in the first row of the xref table. The PDF parser then proceeds to think it's reading the object ID of an xref *stream*, and after that it just gets hopelessly confused.
I noticed that the pointer to the previous xref table is also off by a similar amount. Could it be that something in the pipeline inserted extra bytes somewhere near the start of the file? Accidentally saving a binary file as text sometimes produces errors of this type (due to newline handling, for example).

PyHanko's PDF parser is mostly a holdover from PyPDF2. Usually, it would try to find the start of the xref table by itself in cases like this, but because the byte under the `startxref` pointer happened to be a numerical digit, that piece of logic didn't trigger properly. I'll look into it, but I can't promise anything right now :)

**Comment by MatthiasValvekens** [comment]
I did some more forensics on your file, and the ByteRange of the signature is off by the exact same amount (21 bytes shorter than expected). This suggests that the corruption occurred *after* the signature was produced. What I suspect happened is the following: the content to add to the signed PDF was prepared (correctly) in-memory, but when saving the second revision to disk, something got messed up.

This isn't even necessarily the fault of the signing tool that was used; it could be that the output stream it was writing to was of the wrong type, or something of that nature (but that's a guess).

**Comment by gchehab** [comment]
Hey Matthias,

It actually makes sense, this file was generated through a websocket server commanded by a set of javascript clients, perhaps there is something wrong in the base64 and serialization processing. I´ll revise the whole implementation.

Thanks very much for your help and support.

Guilherme

**Comment by MatthiasValvekens** [comment]
Yes, the signature was invalidated in the saving process, I checked by computing the hashes by hand :)

It's possible to read files like this if you have a sufficiently fault-tolerant PDF parser, and I could certainly make some improvements in that respect; I'll add it to my backlog. The signature would remain invalid either way, though. Thanks for the report! More data is always better.
