### ISSUE TITLE
duplicate serial number in used certificates

### ISSUE THREAD

**Issue by m32** [MatthiasValvekens/pyHanko#206]
Hi Matthias,

There is a duplicate serial number in the certificates used, it can lead to confusion.

openssl x509 -in interm.cert.pem -text |grep Serial
openssl x509 -in signer1.cert.pem -text |grep Serial

**Comment by MatthiasValvekens** [comment]
Hi Grzegorz,


IIRC there is no expectation of uniqueness for serial numbers, right? Only
the issuer<>serial combination is supposed to be unique AFAIK.

I’ll check X.509 and RFC 5280 when I’m at my desk. Anyway I’m pretty sure
that those certs have different issuers. :)

**Comment by MatthiasValvekens** [comment]
RFC 5280 has the following to say about uniqueness of serials (emphasis mine):

> The serial number MUST be a positive integer assigned by the CA to
   each certificate.  It MUST be unique for each certificate **issued by a
   given CA (i.e., the issuer name and serial number identify a unique
   certificate)**.  CAs MUST force the serialNumber to be a non-negative
   integer.

Indeed, checking both certs you mentioned shows that the serials coincide, but the issuer is different, so there should not be any confusion in practice. :)

```
$ openssl x509 -in root/interm.cert.pem -text -noout | grep -E '(Issuer|Serial)'
        Serial Number: 4097 (0x1001)
        Issuer: C=BE, O=Example Inc, OU=Testing Authority, CN=Root CA
$$ openssl x509 -in interm/signer1.cert.pem -text -noout | grep -E '(Issuer|Serial)'
        Serial Number: 4097 (0x1001)
        Issuer: C=BE, O=Example Inc, OU=Testing Authority, CN=Intermediate CA
```

**Comment by m32** [comment]
In fact, you're right. However, this coincidence caused me a slight panic.

**Comment by MatthiasValvekens** [comment]
> In fact, you're right. However, this coincidence caused me a slight panic.

For what it's worth (not much), the default behaviour of `openssl ca` is to assign serial numbers in increasing order starting from `4096`. As such, there are tons of certs with coinciding serial numbers generated by `openssl`, but it's not an issue in practice since the issuers are different.

Since `openssl ca` is the tool I originally used to generate my test certs, I adopted a similar convention when I started [Certomancer](https://github.com/MatthiasValvekens/certomancer) to take over that job.
