### ISSUE TITLE
Check size estimate

### ISSUE THREAD

**Issue by peteris-zealid** [MatthiasValvekens/pyHanko#23]
https://github.com/MatthiasValvekens/pyHanko/blob/022ac7cb3d4a2248634784b88f073ab0f1702bc3/pyhanko/sign/signers/pdf_signer.py#L1240

According to my calculations `bytes_reserved ~ 3 * len(test_signature_cms.dump())` and this is not the 50% extra placeholder that was expected.

Proposed solution
```
            test_len = len(test_signature_cms.dump())          
            # External actors such as timestamping servers can't be relied on to
            # always return exactly the same response, so we build in a 50%
            # error margin (+ ensure that bytes_reserved is even)
            bytes_reserved = test_len * 3 // 4 * 2                 
```

This problem is in one more place in this file.

**Comment by MatthiasValvekens** [comment]
I was a little confused at first, but I believe the existing code is actually correct. The reason is that the CMS bytes have to be encoded hexadecimally in the PDF file, hence why we need to allocate _twice_ the expected byte length of the DER-encoded CMS payload. This is also the reason for insisting on having `bytes_reserved` be even. See also here: https://github.com/MatthiasValvekens/pyHanko/blob/3324683ebc80b01c7596f0a53a4e973795ecc883/pyhanko/sign/signers/pdf_byterange.py#L316-L323.

Granted, that explanation isn't referenced anywhere in `pdf_signer.py`, so I guess I should duplicate that warning in `pdf_signer.py` in a couple places.


Does that address your question, or did I misinterpret your concerns?

**Comment by peteris-zealid** [comment]
Yes, the confusion was about hex encoding. Everything makes sense now. Maybe the comment should be improved, but I will close this issue.
