### ISSUE TITLE
'IndirectObject' object is not iterable when using validate_pdf_ltv_signature

### ISSUE THREAD

**Issue by ttwellmann** [MatthiasValvekens/pyHanko#4]
My use case is that I want to validate on a server that signatures in certain documents (signed with Adobe Reader) fulfill some specific requirements (comply with PAdES LT or LTA).

This is my fiddle code 
```
with open('extCades_Test document.pdf', 'rb') as doc:
    r = PdfFileReader(doc)
    sig = r.embedded_signatures[0]

    print(sig.signer_cert.subject.native.get('common_name'))
    
    status = validate_pdf_ltv_signature(sig,  
        RevocationInfoValidationType.PADES_LT, 
        key_usage_settings = KeyUsageConstraints(key_usage=set(['digital_signature', 'non_repudiation'])), 
        validation_context_kwargs={'trust_roots': [root_cert2, root_cert, ts_root_cert]})
    print(status.pretty_print_details())
```
which causes this exception:
```
Traceback (most recent call last):
  File "c:\Users\ttwellmann\Desktop\byHanko.py", line 55, in <module>
    status = validate_pdf_ltv_signature(sig,
  File "C:\Users\ttwellmann\AppData\Local\Programs\Python\Python38\lib\site-packages\pyhanko\sign\validation.py", line 1511, in validate_pdf_ltv_signature
    dss = DocumentSecurityStore.read_dss(reader)
  File "C:\Users\ttwellmann\AppData\Local\Programs\Python\Python38\lib\site-packages\pyhanko\sign\validation.py", line 1924, in read_dss
    for cert_ref in dss_dict.get('/Certs', ()):
TypeError: 'IndirectObject' object is not iterable
```
The signature in the text document is level B-LT, has an external timestamp and was created with Adobe Reader DC. 

**Expected behavior**
I would have expected that the function returns information about any missing information in the signature, but not an exception
.
**Environment (please complete the following information):**
Window 10, python 3.8.x, pyHanko 0.4.0

**Additional context**
I

**Comment by MatthiasValvekens** [comment]
Ah, yes, I see the problem. Apparently I forgot that `.get()` does not dereference objects, so that piece of code would fail if the DSS entries aren't direct objects. This is a silly mistake, and should be pretty easy to fix. Are you OK with a fix applied to the master branch, or would you prefer that I provide a "minimal" patch on top of 0.4.0? It's all alpha software regardless, but after 0.4.0 I messed with the dependencies a little.


Thanks for reporting the bug, by the way! This kind of oversight is hard to spot without "real" usage testing.

**Comment by MatthiasValvekens** [comment]
I pushed a fix + regression test to master (commit 48b3ed5) and cherry-picked it into the hotfix/issue-4 branch (commit 885587d). The latter branches off 0.4.0 directly, so it should apply only minimal changes to your existing setup.

Could you let me know if this resolves your problem? And if not, it'd be hugely useful if you could share the input file that isn't being processed correctly (although I of course understand if you can't due to privacy concerns). Thanks!

**Comment by ttwellmann** [comment]
Hey, thanks for your quick response which actually solved the issue. 

Also thanks for your note. I think your code already fulfills my requirements. We have an in-house Django application that coordinates the signing process for internal documents. Once a new signature has been added to a file it should just check if the signature has an external timestamp and also includes the verification information for long-term validity. Just to make sure nobody used a miss-configured Acrobat Reader.

The project is really promising as I'don know any open-source alternatives (except commercial-like PDFTron). Thanks for your work!

Let me check if I can get test certificate from our CA (german Bundesdruckerei). I don't want to have my signature (issued by my employer) in a public repository although the document is just an empty PDF. 

What surprises me now is that the library says that there is no path to trust anchor although all required certificates in the list give as validation_context_kwargs. The timestamp is classified as trusted (its root is also one of the three input certificates)

**Comment by MatthiasValvekens** [comment]
Thanks! That's good news.

I started work on this library precisely because I couldn't find any (gratis) FOSS tools, especially in the Python space. It's good to hear that other people feel the same way.

> What surprises me now is that the library says that there is no path to trust anchor although all required certificates in the list give as validation_context_kwargs. The timestamp is classified as trusted (its root is also one of the three input certificates)

It's hard to diagnose this without access to the actual file, but does the chain of trust of your signer's certificate to your root(s) happen to pass through an intermediate AATL certificate authority along the way? It seems that Acrobat (sometimes?) only adds validation info until it hits a well-known AATL cert, at which point it considers the chain of trust valid. PyHanko doesn't know about the AATL by default, so it will complain that it can't validate the chain of trust to a trusted root certificate.
Most certificates on the AATL will probably have _some_ path that leads to a trusted root on your system, but chances are that Acrobat didn't embed enough revocation info into the file to establish that to pyHanko's satisfaction.

Again, I don't know if this is the issue you're facing, but if that's the case, you can always tell pyHanko to treat the intermediate AATL CA in question as a trust anchor.

I should look into ways to make pyHanko aware of trust lists beyond the system trust, really. At least that'd make it easier to emulate Acrobat's behaviour when required.


By the way, if you're comfortable sending files by email, you can do so at pyhanko.samples {{at mark goes here}} mvalvekens.be. You can also encrypt them with
[my GPG key](https://github.com/MatthiasValvekens/pyHanko/files/6018756/matthias-gpg.asc.txt), if you prefer that. I generally hand-craft sample files for the test suite, so the file won't be made public. Anyway, it's your call, just putting the options out there :)

**Comment by ttwellmann** [comment]
Will do that! Thanks!
