### ISSUE TITLE
merge 2 or 2+ pages into 1 single page

### ISSUE THREAD

**Issue by hero100era** [MatthiasValvekens/pyHanko#6]
Is there any demo how to merge 2 or 2+  pages into 1 single page like pyPDF2?
I have looked to the folder pyhanko-tests, however, due to I'm not familiar the low level details how the PDF was assmbled, the atempt to add a qr code imgage and a text with link was never success.

Would you please advise the equivalent of pyPDF2 as bellow for pyhanko?

```
    newPdf = PdfFileReader(buffer)
    filename = os.path.join(path, self.draft)
    existingPdf = PdfFileReader(open(filename, 'rb'))
    page = existingPdf.getPage(0)
    page.mergePage(newPdf.getPage(0))
    output = PdfFileWriter()
    for page in range(existingPdf.getNumPages()):
        output.addPage(existingPdf.getPage(page))
    output.write(buffer)
```

**Comment by MatthiasValvekens** [comment]
Hey, I dropped this functionality when I forked (part of) PyPDF2, because I considered it out of scope for pyHanko (at least for now) and didn't want to be on the hook for maintaining it. The reason being that merging pages is very straightforward in _most_ cases, but getting it 100% right is a little tricky.

The reason for the difficulty has to do with page resources. If both pages use a resource with the same name (which is by no means rare), you can't just merge the resource dictionaries together without modification. This can be dealt with by changing resource names, but that requires reencoding the content stream, which requires a parser that can tokenise PDF content streams, etc. Granted, that particular problem can be sidestepped by first converting one of the pages to a form XObject before merging, but that method isn't completely foolproof either if the PDF file is tagged.

Anyway, bottom line is that this is harder than it looks (in general), and it isn't very high up on my priority list because pyHanko wasn't meant to be a general-purpose PDF manipulation library in the first place. That said, I don't want to half-ass a high-level function like this either, so if I ever end up putting in a merge feature, I'm going to take my time to do it the proper way :)

Are you sure that merging pages is the only way forward? If so, using `import_page_as_xobject` should get you halfway there if you don't care about tags. You can then add that XObject to the other page's resource dictionary and draw it with the `Do` operator in PDF. I don't have time to put together a fully fleshed-out example right now (and probably won't until the end of the week), but this might serve as a starting point. :)

**Comment by MatthiasValvekens** [comment]
Closing this one as `wontfix` due to lack of activity. Feel free to reopen if there's new information. :)
