### ISSUE TITLE
Error: Failed to read PDF file.

### ISSUE THREAD

**Issue by ghoshpushpendu** [MatthiasValvekens/pyHanko#68]
1 uploads/61cd28fb986c7817124531770sample.pdf uploads/1_out_61cd28fb986c7817124531770sample.pdf uploads/1_signed_61cd28fb986c7817124531770sample.pdf
Executing Command : pyhanko sign addfields --field  1/1,1,100,50/signature1 uploads/61cd28fb986c7817124531770sample.pdf uploads/1_out_61cd28fb986c7817124531770sample.pdf
(node:7556) UnhandledPromiseRejectionWarning: Error: Command failed: pyhanko sign addfields --field  1/1,1,100,50/signature1 uploads/61cd28fb986c7817124531770sample.pdf uploads/1_out_61cd28fb986c7817124531770sample.pdf
2021-12-30 10:16:56,111 - pyhanko.cli - ERROR - Failed to read PDF file.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyhanko/cli.py", line 80, in pyhanko_exception_manager
    yield
  File "/usr/local/lib/python3.9/site-packages/pyhanko/cli.py", line 1205, in add_sig_field
    writer = IncrementalPdfFileWriter(infile)
  File "/usr/local/lib/python3.9/site-packages/pyhanko/pdf_utils/incremental_writer.py", line 41, in __init__
    prev = PdfFileReader(input_stream)
  File "/usr/local/lib/python3.9/site-packages/pyhanko/pdf_utils/reader.py", line 617, in __init__
    self.read()
  File "/usr/local/lib/python3.9/site-packages/pyhanko/pdf_utils/reader.py", line 972, in read
    self._read_xrefs()
  File "/usr/local/lib/python3.9/site-packages/pyhanko/pdf_utils/reader.py", line 940, in _read_xrefs
    raise PdfReadError(
pyhanko.pdf_utils.misc.PdfReadError: Xref table contains orphaned higher generation objects: 78 39 obj,80 37 obj,82 35 obj,84 33 obj,86 31 obj,101 1 obj

**Comment by MatthiasValvekens** [comment]
This is probably not a bug, but intended behaviour. Quoting from ISO 32000-2:2020, 7.5.4 "Cross-reference table":

> Except for object number 0, all objects in the cross-reference table shall initially have generation numbers of 0. When an indirect object is deleted, its cross-reference entry shall be marked free and it shall be added to the linked list of free entries. The entry’s generation number shall be incremented by 1 to indicate the generation number to be used the next time an object with that object number is created.

PyHanko's xref processing logic enforces these restrictions in that it checks for corresponding "free" entries in the xref history whenever it encounters nonzero generation numbers. "Regular" PDF viewers don't care, but since the interpretation of these generation numbers differs between implementations, I believe that signing tools should be suspicious of them by default.

Those nonzero generation numbers are extremely rare in modern PDF software, by the way. So I'm guessing that your sample files are very old, or the software that produced them is outdated (in addition to being buggy). Can you share the file(s) in question? Without sample files, it's hard to say whether this is a bug on our end or not.

**Comment by ghoshpushpendu** [comment]
[61cd28fb986c7817124531770sample.pdf](https://github.com/MatthiasValvekens/pyHanko/files/7792797/61cd28fb986c7817124531770sample.pdf)

This seems to be the file.

**Comment by MatthiasValvekens** [comment]
Yeah, there's only one revision in that file, so there shouldn't be any nonzero generation numbers whatsoever. I'm not sure how those got there (I suspect a faulty post-processor), but I don't consider this a bug in pyHanko.

I'd be willing to consider skipping these checks in nonstrict mode, though. Just be aware that messing with xref interpretation in signed or to-be-signed documents can be pretty dangerous: faulty or ambiguous xref tables can (in principle) cause a given PDF to display different content depending on the viewer, which effectively invalidates any signatures if the difference is significant to the document's interpretation. As such, I'm not going to change the defaults.
