### ISSUE TITLE
Can't install dependencies (PKCS11)

### ISSUE THREAD

**Issue by joseavegaa** [MatthiasValvekens/pyHanko#72]
**Describe the bug**
I can install pyHanko normally, but when trying to install python-pkcs11, I get an error message. I know this isn't completely related to this project, but I've reported the bug [here](https://github.com/danni/python-pkcs11/issues/133) and still haven't got an answer. Is there any other way to make pyHanko work with a RSA PKCS1 Smart Card?  

**To Reproduce**
Try to install python-pkcs11 on a new env.

**Expected behavior**
Have pyHanko installed along with the needed dependencies. 

**Environment (please complete the following information):**
 - OS: Windows 10 / 11, 64x
 - Python: 3.10
 - pyHanko: 0.11.0

**Additional context**
I need a way to install python-pkcs11 on a new env, or a way to have pyHanko work with a Smart Card.

**Comment by MatthiasValvekens** [comment]
Since the install process for `python-pkcs11` doesn't touch pyHanko at all, I'm afraid there's nothing I can do within pyHanko to address your problem... I'll close this issue and continue the discussion in the tracker for `python-pkcs11`. Even if we figure out the problem over here, that's not going to be of much help to the maintainer(s) of `python-pkcs11`. :)
